name: build-publish-workflow

on: 
  workflow_dispatch: 
  push: 
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run Tests
        run: mvn -B clean test
  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Create Package
        run: mvn -B clean package -DskipTests
      - name: upload jar file
        uses: actions/upload-artifact@v3
        with:
          name: api-jar
          path: target/*.jar
  publish-docker:
    runs-on: ubuntu-latest
    needs: [package]
    steps: 
      - name: download jar file
        uses: actions/download-artifact@v3
        with:
          name: api-jar
          path: target

      - name: display artifact
        run: |
          ls -l
          echo "In target folder"
          ls target


    
    
